### ISSUE TITLE
OutputFileMode must be string

### ISSUE THREAD

**Issue by peschmae** [thegeeklab/prometheus-pve-sd#185]
With version 2.4.0 the app can no longer be started, since the output file mode needs to be an octal, and can't be a string.

The error thrown is
```
File "/usr/local/lib/python3.10/site-packages/prometheuspvesd/cli.py", line 177, in _write chmod(self.config.config["output_file"], self.config.config["output_file_mode"]) TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by xoxys** [comment]
Argh... Yeah, I missed adding the required octal int cast, sorry. PR created to fix it, Im going to yank the 2.4.0 release and will prepare a new one tomorrow.

**Comment by peschmae** [comment]
Thanks a lot for your work on this tool, I really like it and it helps me a lot with my setup :)

**Comment by xoxys** [comment]
Your welcome :) Thank you too for all the contributions, ideas and reports.
