### ISSUE TITLE
Refactoring Proxmox API interactions

### ISSUE THREAD

**Issue by peschmae** [thegeeklab/prometheus-pve-sd#195]
While trying to write some test for the `propagate` method, I struggled quite a bit with trying to mock the Proxmox API calls.

Looking at the API calls and the implementation of the client, I thought it might make sense to refactor this a bit, and put it into it's own class/service.

This way it would get easier to mock the API calls, since it's just possible to mock the whole service, and define what's returned from there.

It would also allow to do some centralized exception handling for the Proxmox API, and makes managing API changes (if they happen) easier.

Would you be interested in a pull request for this?
If so, what would you prefere for the naming? Calling it a ProxmoxClient or a ProxmoxService?

**Comment by xoxys** [comment]
We use the `proxmoxer` library client already and the single point of use is the initialized client object in discovery.py, so I don't think moving it to another wrapper class helps. What is bad, or what was the issue, while using  `mocker.create_autospec(ProxmoxAPI)` to mock the `proxmoxer` API client?

**Comment by peschmae** [comment]
The issue I has was that there is only the `get` function that is called.
And when trying to mock all the calls done in `propagate` I would need to mock the get function in a way, that has a return for each of the different calls done, and does the differentiation which call is done.

Moving it to a wrapper that then implements functions like `get_all_nodes`, `get_all_vms`, `get_network_interfaces`, would make mocking a bit easier.

**Comment by xoxys** [comment]
Ah, yeah got it. I was using https://github.com/thegeeklab/prometheus-pve-sd/blob/main/prometheuspvesd/test/unit/test_discovery.py#L20-L29 and a lambda function https://github.com/thegeeklab/prometheus-pve-sd/blob/main/prometheuspvesd/test/unit/test_discovery.py#L101.

This way I was able to achieve what I wanted, but I'm fine with a small wrapper class as well. Calling it `ProxmoxClient` works for me as well.

**Comment by xoxys** [comment]
Fixed by https://github.com/thegeeklab/prometheus-pve-sd/pull/196
