### ISSUE TITLE
IPs are not fetch from QEMU guest agents informations

### ISSUE THREAD

**Issue by Tash1nka** [thegeeklab/prometheus-pve-sd#578]
Hi,

I'm currently using this and have noted that when using snippets files for cloud-init configurations, IPv4 and IPv6 meta labels return `False` even if the VMs have the QEMU guest agent running.

IPs are displayed correctly on the Proxmox UI.

Also questions about this:
- What are the required/appropriate Proxmox user permissions for the SD to get every information ?
- Could the `False` values came from the fact that VMs have multiple IPs, either bridges or NICs ?

**Comment by AlexandrBoltris** [comment]
I had the same issue until I added the `VM.Monitor` privilege.

After some investigation, I found that those two privileges are enough:
- `VM.Audit`
- `VM.Monitor`

**Comment by xoxys** [comment]
Awesome! Thanks for letting us know. Should we document this and e.g. add a Requirements section to https://prometheus-pve-sd.geekdocs.de/usage/getting-started/?
